
-- Seleccionar la Base de Datos


USE ADS_DB;

--iNSERTANDO TABLAS:

INSERT INTO ROL(IDROL,NOMBRE) VALUES(1,'Administrador');
INSERT INTO ROL(IDROL,NOMBRE) VALUES(2,'Operador');
INSERT INTO ROL(IDROL,NOMBRE) VALUES(3,'Usuario');


INSERT INTO EMPLEADO(APELLIDO,NOMBRE,DNI,DIRECCION,TELEFONO,EMAIL)
VALUES('CORONEL','GUSTAVO','000000000','NARNIA','111-1111','GUSTAVO@GMAIL.COM');

INSERT INTO EMPLEADO(APELLIDO,NOMBRE,DNI,DIRECCION,TELEFONO,EMAIL)
VALUES('MOSCOL','HECTOR','123456789','LOS OLIVOS','123-4567','HECTORM@GMAIL.COM');

INSERT INTO EMPLEADO(APELLIDO,NOMBRE,DNI,DIRECCION,TELEFONO,EMAIL)
VALUES('GUERRA','EDUARDO','456789123','INDEPENDENCIA','666-1234','YAYITO@GMAIL.COM');


-- USUARIO

INSERT INTO USUARIO (IDEMPLEADO,IDROL,USUARIO,CLAVE,ESTADO)
VALUES(1,1,'gustavo',HashBytes('EGCC1','gustavo'),1);

INSERT INTO USUARIO (IDEMPLEADO,IDROL,USUARIO,CLAVE,ESTADO)
VALUES(2,2,'eduardo',HashBytes('EGCC2','eduardo'),1);


--NIVEL

insert into NIVEL(IDNIVEL, NOMBRE) values(1,'PRIMARIA');
insert into NIVEL(IDNIVEL, NOMBRE) values(2,'SECUNDARIA');

--SECCION

insert into SECCION(IDSECCION,IDNIVEL,IDGRADO,VACANTES,MATRICULADOS,AULA) 
values ('E1001',1,101,20,0,'B100');

insert into SECCION(IDSECCION,IDNIVEL,IDGRADO,VACANTES,MATRICULADOS,AULA) 
values ('E1002',1,105,20,0,'D200');

insert into SECCION(IDSECCION,IDNIVEL,IDGRADO,VACANTES,MATRICULADOS,AULA) 
values ('E1001',2,203,20,0,'C400');

--TOBLIGACIONES 

insert into TOBLIGACION(tobligacion,nombre) values(1,'CUOTA INGRESO');
insert into TOBLIGACION(tobligacion,nombre) values(2,'PAGO MATRICULA');
insert into TOBLIGACION(tobligacion,nombre) values(3,'PAGO PENSION');

--OBLIGACIONES

SET IDENTITY_INSERT dbo.OBLIGACION ON;  
GO

INSERT INTO OBLIGACION(idobligacion,descrip,codalumno,tobligacion,importe,fecven,
idmatricula,audempleado,audfecha)
VALUES(1,'PAGO X INGRESO',1,1,1000.0,'20170220',NULL,1,GETDATE());

INSERT INTO OBLIGACION(idobligacion,descrip,codalumno,tobligacion,importe,fecven,
idmatricula,audempleado,audfecha)
VALUES(2,'PAGO X INGRESO',3,1,1000.0,'20170220',NULL,1,GETDATE());

INSERT INTO OBLIGACION(idobligacion,descrip,codalumno,tobligacion,importe,fecven,
idmatricula,audempleado,audfecha)
VALUES(3,'PAGO X INGRESO',2,1,1000.0,'20170220',NULL,1,GETDATE());

SET IDENTITY_INSERT dbo.OBLIGACION OFF;  
GO